{{ if .Values.openshift -}}
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: hnc
redirectURIs:
  - https://{{ tpl .Values.ocp.ingress.host $ }}
secret: {{ .Values.ocp.client_secret }}
grantMethod: auto
{{- end }}
