apiVersion: v1
kind: Service
metadata:
  name: hnc-ui
  namespace: hnc-ui
  annotations:
    {{ if .Values.openshift -}}
    service.alpha.openshift.io/serving-cert-secret-name: hnc-tls
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 8443
    protocol: TCP
    targetPort: web
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app: hnc-ui
