{{- if .Values.openshift }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hnc-ui
spec:
  endpoints:
  - path: /metrics
    port: web
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app: hnc-ui
{{- end }}
