name: Release Images

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: New release version
        required: true

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: image
          push: true
          tags: ghcr.io/zfrhv/hnc-ui:${{ inputs.version }}
