name: Release All

on:
  workflow_dispatch:

jobs:
  release-chart:
    uses: zfrhv/hnc-ui/.github/workflows/helm-build.yml@main
  release-image:
    uses: zfrhv/hnc-ui/.github/workflows/docker-image.yml@main
